added HashMap
VolodyaSoldatenkov/hashmap-review pull request #1
Opened 2019-03-05 21:18 UTC by VolodyaSoldatenkov

Никита Солодовников

2019-03-10 14:27 UTC, Skird requested changes

2019-03-10 14:27 UTC, Skird commented on HashMap.h
> +    HashMap(const HashMap& rhs) : mData(rhs.mData), mHash(rhs.mHash), mSize(rhs.mSize) {}
Зачем все это писать?
Есть негласное правило: в связке "конструктор копирования - операторы присваивания (assignment, move assignment) - move конструктор - деструктор" вам нужно либо ничего, либо все
Не вижу здесь повода писать свои костыли, все и так прекрасно замувается дефолтным конструктором

2019-03-10 14:27 UTC, Skird commented on HashMap.h
> +    HashMap(Iter begin, Iter end, Hash hash = Hash()) : mHash(hash), mSize(std::distance(begin, end)) {
Не будет работать для InputIterator, std::distance тут же явно лишний, можно просто в цикле инкрементировать
Еще хороший тон явно указывать в typename какой итератор структура готова принять

2019-03-10 14:27 UTC, Skird commented on HashMap.h
> +    class iterator : public std::iterator<std::forward_iterator_tag, StoredType> {
Два класса различаются только типами и содержат дословно один и тот же код. Нужно придумать, как унифицировать реализацию

2019-03-10 14:27 UTC, Skird commented on HashMap.h
> +        if (loadFactor() > 0.5)
Магические константы обычно именуют и выносят куда-то, а то можно в одном месте 0.5 исправить, а в другом не исправить

2019-03-10 14:27 UTC, Skird commented on HashMap.h
> +    std::pair<iterator, bool> insert(StoredType&& in) {
Если уж объявлять insert(T&&), то зачем дублировать код, а не реализовать один insert через другой?

2019-03-10 14:27 UTC, Skird commented on HashMap.h
> +    void swap(HashMap& rhs) noexcept(std::is_nothrow_swappable_v<Hash>) {
Вообще говоря более стандартный способ сделать объект Swappable это сделать функцию в родительском namespace
https://en.cppreference.com/w/cpp/named_req/Swappable

2019-03-10 15:22 UTC, VolodyaSoldatenkov commented on HashMap.h
> +    HashMap(const HashMap& rhs) : mData(rhs.mData), mHash(rhs.mHash), mSize(rhs.mSize) {}
К сожалению, нет, не всё замувается. Из-за константности ключа не компилируются присваивания, сгенерированные по умолчанию. По крайней мере, в GCC 4.9.

2019-03-17 13:46 UTC, Skird commented on HashMap.h
> +    HashMap(const HashMap& rhs) : mData(rhs.mData), mHash(rhs.mHash), mSize(rhs.mSize) {}
Это последствия того, что хранится вектор не CopyAssignable типа. Это конечно в современных плюсах допустимо, но последствия налицо

2019-03-23 17:04 UTC, Skird approved these changes

2019-03-23 17:05 UTC, merged